apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bvk12/tomcatcercuit26.git' # Your Git URL
    targetRevision: HEAD
    path: prod-app # Path to your Helm files inside Git
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Automatically creates the UAT namespace

